apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::140023388050:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-uCvaPkv7utHE
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::140023388050:user/suresh
      username: suresh  
kind: ConfigMap
metadata:
  creationTimestamp: "2025-07-05T05:44:53Z"
  name: aws-auth
  namespace: kube-system
  uid: fca777a0-2350-48fb-85ae-28e914b6e39d